USE onboarding_system;

CREATE TABLE IF NOT EXISTS usuarios_acesso (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    pin VARCHAR(20) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE dados_loja ADD COLUMN IF NOT EXISTS usuario_id INT NULL AFTER id;
ALTER TABLE categorias ADD COLUMN IF NOT EXISTS usuario_id INT NULL AFTER id;
ALTER TABLE ativos_fisicos ADD COLUMN IF NOT EXISTS usuario_id INT NULL AFTER id;
ALTER TABLE usuarios_internos ADD COLUMN IF NOT EXISTS usuario_id INT NULL AFTER id;
ALTER TABLE gerentes_loja ADD COLUMN IF NOT EXISTS usuario_id INT NULL AFTER id;
ALTER TABLE industrias ADD COLUMN IF NOT EXISTS usuario_id INT NULL AFTER id;
ALTER TABLE dados_bancarios ADD COLUMN IF NOT EXISTS usuario_id INT NULL AFTER id;
ALTER TABLE plantas_loja ADD COLUMN IF NOT EXISTS usuario_id INT NULL AFTER id;
ALTER TABLE ativos_digitais ADD COLUMN IF NOT EXISTS usuario_id INT NULL AFTER id;
ALTER TABLE alcadas ADD COLUMN IF NOT EXISTS usuario_id INT NULL AFTER id;
ALTER TABLE header_clientes ADD COLUMN IF NOT EXISTS usuario_id INT NULL AFTER id;
