ALTER TABLE diagnostico_loja
  ADD COLUMN dados_loja_id INT NULL,
  ADD COLUMN preenchido_por VARCHAR(255) NULL,
  ADD COLUMN loja_nome_numero VARCHAR(255) NULL,
  ADD COLUMN endereco_loja VARCHAR(500) NULL,
  ADD COLUMN banner_estacionamento VARCHAR(20) NULL,
  ADD COLUMN banner_estacionamento_quantidade VARCHAR(80) NULL,
  ADD COLUMN banners_gradil_estacionamento VARCHAR(20) NULL,
  ADD COLUMN banners_gradil_estacionamento_qtd VARCHAR(80) NULL,
  ADD COLUMN antena_alarme_entrada VARCHAR(20) NULL,
  ADD COLUMN antena_alarme_entrada_qtd VARCHAR(80) NULL,
  ADD COLUMN placas_cancela_estacionamento VARCHAR(20) NULL,
  ADD COLUMN placas_cancela_estacionamento_qtd VARCHAR(80) NULL,
  ADD COLUMN quantidade_checkouts VARCHAR(80) NULL,
  ADD COLUMN reguas_check_stand VARCHAR(20) NULL,
  ADD COLUMN reguas_check_stand_qtd VARCHAR(80) NULL,
  ADD COLUMN quantidade_pontas_gondola VARCHAR(80) NULL,
  ADD COLUMN quantidade_portas_pontas_refrigeradas VARCHAR(80) NULL,
  ADD COLUMN quantidade_orelhas_ponta_gondola VARCHAR(80) NULL,
  ADD COLUMN ilhas_loja VARCHAR(20) NULL,
  ADD COLUMN ilhas_loja_qtd VARCHAR(80) NULL,
  ADD COLUMN localizacao_principais_ilhas TEXT NULL,
  ADD COLUMN quantidade_display_chao VARCHAR(80) NULL,
  ADD COLUMN backlights VARCHAR(20) NULL,
  ADD COLUMN backlights_qtd VARCHAR(80) NULL,
  ADD COLUMN exclusividade_ponta_backlight VARCHAR(20) NULL,
  ADD COLUMN banners_interior VARCHAR(20) NULL,
  ADD COLUMN banners_interior_detalhes TEXT NULL,
  ADD COLUMN retail_media VARCHAR(20) NULL,
  ADD COLUMN retail_media_ativos TEXT NULL,
  ADD COLUMN televisores_internos VARCHAR(20) NULL,
  ADD COLUMN televisores_internos_qtd VARCHAR(80) NULL,
  ADD COLUMN elevadores VARCHAR(20) NULL,
  ADD COLUMN elevadores_qtd VARCHAR(80) NULL,
  ADD COLUMN radio_interna VARCHAR(20) NULL,
  ADD COLUMN escadas_esteiras_rolantes VARCHAR(20) NULL,
  ADD COLUMN escadas_esteiras_rolantes_qtd TEXT NULL,
  ADD COLUMN quantidade_freezers VARCHAR(80) NULL,
  ADD COLUMN quantidade_pontas_ilha_congelados VARCHAR(80) NULL,
  ADD COLUMN displays_laterais_lfc VARCHAR(20) NULL,
  ADD COLUMN displays_laterais_lfc_qtd VARCHAR(80) NULL,
  ADD COLUMN walk_in_cooler VARCHAR(20) NULL,
  ADD COLUMN walk_in_cooler_portas VARCHAR(80) NULL,
  ADD COLUMN quantidade_portas_bebidas VARCHAR(80) NULL,
  ADD COLUMN quantidade_portas_laticinios VARCHAR(80) NULL,
  ADD COLUMN quantidade_portas_congelados_refrigerados VARCHAR(80) NULL,
  ADD COLUMN quantidade_carrinhos VARCHAR(80) NULL,
  ADD COLUMN quantidade_cestas VARCHAR(80) NULL,
  ADD COLUMN quantidade_check_stands VARCHAR(80) NULL,
  ADD COLUMN pontas_gondola_refrigeradas_detalhes TEXT NULL;

ALTER TABLE diagnostico_loja
  ADD COLUMN dados_loja_id INT NULL,
  ADD INDEX idx_diagnostico_loja_dados_loja_id (dados_loja_id),
  ADD CONSTRAINT fk_diagnostico_loja_dados_loja
    FOREIGN KEY (dados_loja_id) REFERENCES dados_loja(id) ON DELETE SET NULL;
